export const REQUEST_RACCOON_GIFS = "gifslibrary/REQUEST_RACCOON_GIFS";
export const RECEIVE_RACCOON_GIFS = "gifslibrary/RECEIVE_RACCOON_GIFS";

export const REQUEST_FAVORITE = "gifslibrary/REQUEST_FAVORITE";
export const RECEIVE_FAVORITE = "gifslibrary/RECEIVE_FAVORITE";

export const REQUEST_UNFAVORITE = "gifslibrary/REQUEST_UNFAVORITE";
export const RECEIVE_UNFAVORITE = "gifslibrary/RECEIVE_UNFAVORITE";

export const REQUEST_UPDATE_FAVORITE_LIST =
  "gifslibrary/REQUEST_UPDATE_FAVORITE_LIST";
export const RECEIVE_UPDATE_FAVORITE_LIST =
  "gifslibrary/RECEIVE_UPDATE_FAVORITE_LIST";
